name: CI/CD - DrViKi App

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run basic test
        run: |
          python app.py &
          sleep 5
          curl http://localhost:8080

      - name: Build Docker image
        run: docker build -t drviki-app .

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v0.2.3
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
